# .github/workflows/integracion-dev.yml

name: CI - Integración en Dev # Nombre visible del workflow en GitHub Actions

on:
  push:
    branches:
      - dev
  pull_request: # <-- Asegúrate de que esta sección esté si la necesitas, o elimínala si solo es 'push'
    branches:
      - dev

jobs: # <-- Esta es la línea 74, asegúrate de que no tenga espacios delante y esté alineada con 'on:' y 'name:'
  build_and_test_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '18', '20' ]

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar Dependencias del Proyecto
        run: npm install

      - name: Instalar Navegadores de Playwright
        run: npx playwright install --with-deps chromium firefox webkit

      - name: Construir Aplicación React (Vite)
        run: npm run build

      - name: Servir Aplicación Compilada para Pruebas Playwright
        run: npx serve -l 5173 dist & npx wait-on http://localhost:5173 -t 60000
        working-directory: .

      - name: Ejecutar Pruebas Playwright
        run: npx playwright test
        env:
          CI: true

      - name: Subir Reporte de Pruebas Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5